service: shop-import-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: dev
  httpApi:
    cors: true

environment:
  BUCKET: ${env:BUCKET}
  SQS_URL:
    Ref: SQSQueue

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${env:QUEUE_NAME}

iamRoleStatements:
  - Effect: "Allow"
    Action: s3:ListBucket
    Resource: 
      - "arn:aws:s3:::shop-app-import-service"
  - Effect: "Allow"
    Action: "s3:*"
    Resource:
      - "arn:aws:s3:::shop-app-import-service/*"
  - Effect: "Allow"
    Action: "sqs:*"
    Resource: !GetAtt SQSQueue.Arn

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
  dotenv:
    logging: false
    include:
      - BUCKET
      - QUEUE_NAME
      - SQS_URL

functions:
  - importProductsFile:
      handler: handlers/importProductsFile.importProductsFile
      events:
        - httpApi:
            path: /import
            method: get
            request:
              parametrs:
                querystrings:
                  name: true
  - importFileParser:
      handler: handlers/importFileParser.importFileParser
      events:
        - s3:
          bucket: shop-app-import-service
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
            - suffix: .csv
          existing: true