openapi: 3.0.0
info:
  title: products-service-api
  version: 1.0.0-oas3
servers:
  - url: 'https://l0bupdv27h.execute-api.eu-west-1.amazonaws.com/dev'
paths:
  /products:
    get:
      description: Get all products
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          content:
            application/json:
              schema:
                type: string
          description: Internal server error
    post:
      description: Create product
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                count:
                  type: integer
                description:
                  type: string
                price:
                  type: number
                title:
                  type: string
              required: 
                - price
                - title
                - description
      responses:
        '201':
          content:
            application/json:
              schema:
                type: string
          description: Created
        '400':
          content:
            application/json:
              schema:
                type: string
          description: Bad request
        '500':
          content:
            application/json:
              schema:
                type: string
          description: Internal server error
  '/products/{id}':
    get:
      description: Get product by id
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: string id type
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Product'
        '400':
          content:
            application/json:
              schema:
                type: string
          description: Product not found
        '500':
          content:
            application/json:
              schema:
                type: string
          description: Internal server error
components:
  schemas:
    Product:
      type: object
      properties:
        count:
          type: integer
        description:
          type: string
        id:
          type: integer
        price:
          type: number
        title:
          type: string
      required: 
        - price
        - title
        - description