service: authorization-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: dev
  
environment:
  LoraBard: ${env:LoraBard}

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: webpack.config.js
  dotenv:
    logging: false
    include:
      - LoraBard

functions:
  - basicAuthorizer:
      handler: handlers/basicAuthorizer.basicAuthorizer